-- Заполняем MPA
INSERT INTO PUBLIC.MPA (MPA_NAME) VALUES('G');
INSERT INTO PUBLIC.MPA (MPA_NAME) VALUES('PG');
INSERT INTO PUBLIC.MPA (MPA_NAME) VALUES('PG-13');
INSERT INTO PUBLIC.MPA (MPA_NAME) VALUES('R');
INSERT INTO PUBLIC.MPA (MPA_NAME) VALUES('NC-17');

-- Заполняем GENRES
INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES('Комедия');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES('Драма');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES('Мультфильм');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES('Триллер');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES('Документальный');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) VALUES('Боевик');
